security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    # HIÉRARCHIE DES RÔLES
    # Définit l'ordre de puissance des utilisateurs
    role_hierarchy:
        ROLE_ABONNE:      ROLE_USER
        ROLE_AUTEUR:      ROLE_ABONNE
        ROLE_EDITEUR:     ROLE_AUTEUR
        ROLE_DESIGNER:    ROLE_USER
        ROLE_FOURNISSEUR: ROLE_USER
        ROLE_ADMIN:       [ROLE_EDITEUR, ROLE_DESIGNER, ROLE_FOURNISSEUR]

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider

            # Configuration du Login
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                username_parameter: email
                password_parameter: password
                default_target_path: app_home
            
            # Configuration du Logout
            logout:
                path: app_logout
                target: app_login

    # CONTRÔLE D'ACCÈS
    # Note : Symfony s'arrête à la PREMIÈRE règle qui correspond au chemin
    access_control:
        # Pages publiques
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }

        # Pages réservées à des rôles spécifiques (exemples basés sur tes besoins)
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/import-data, roles: ROLE_FOURNISSEUR }
        - { path: ^/design-theme, roles: ROLE_DESIGNER }
        
        # Par défaut, le reste du site est accessible aux utilisateurs connectés (ROLE_USER)
        # - { path: ^/, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10